name: Release Portal Quit
on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    build:
        name: Build Portal Quit
        runs-on: ubuntu-22.04
        steps:
            - name: Check out source code
              uses: actions/checkout@v4

            # Generate version information
            - name: Generate version text file
              run: git describe --tag > quit-version.txt

            # Set an environment variable to the tag we want to use to describe this release for file naming purposes
            - name: Get tag environment variable.
              run: echo "RELEASE_VERSION=$(git describe --tag)" >> $GITHUB_OUTPUT
              id: release-version

            # Install dependencies
            - name: Install dependencies & build software for amd64.
              run: chmod +x ./deploy.sh && ./deploy.sh

            - name: Tar the version and executable files for amd64
              run: tar -cvf amd64-linux-${{ steps.release-version.outputs.RELEASE_VERSION }}.tar -C target/release/ chronokeep-portal-quit ../../quit-version.txt
            - name: Zip amd64 tar
              run: gzip amd64-linux-${{ steps.release-version.outputs.RELEASE_VERSION }}.tar
                
            - name: Create release
              id: create_release
              uses: ncipollo/release-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag: ${{ steps.release-version.outputs.RELEASE_VERSION }}

            - name: Update release asset
              id: upload-release-asset
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: amd64-linux-${{ steps.release-version.outputs.RELEASE_VERSION }}.tar.gz